### ISSUE TITLE
ImportError when running backend

### ISSUE THREAD

**Issue by jessebl** [whitman-books-online/whitman-books-online#152]
I get this locally and on the test server:

```python
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from listing import Listing, allListings
  File "/path/to/repo/backend/api/listing.py", line 5, in <module>
    from book import BookModel  # for error handling, cannot add listing if book not in db
  File "/path/to/repo/backend/api/book.py", line 7, in <module>
    from db import db
ImportError: cannot import name 'db'
```

**Comment by jessebl** [comment]
After conferring with @phillits , I have reverted the change in `db.py` and that fix will be included in an upcoming PR.

**Comment by phillits** [comment]
Sorry to mess up your code, @jessebl.

**Comment by jessebl** [comment]
Don't sweat it! That one is hard to anticipate, and was a super easy fix on top of that.
